### ISSUE TITLE
Resume download on timeout

### ISSUE THREAD

**Issue by toolsche** [tharyckgusmao/Skill-Share-Crawler---DL#23]
Hi,

After I managed to log in with the horrible Capture I tried to download something by id:

internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: read ETIMEDOUT
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:628:25)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! skillshare_dl@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 

It would be great if the the session would be kept and and to have an option to retry and continue or overwrite specific or all failed parts of the videos.

**Comment by tharyckgusmao** [comment]
#5

**Comment by sellmeformoney** [comment]
Me too buddy 😂

**Comment by sellmeformoney** [comment]
Sometimes I think the problem is too many users watching the course so the download just got stuck 😒
