### ISSUE TITLE
not allowing to enter auto or manual auth

### ISSUE THREAD

**Issue by echavez91** [tharyckgusmao/Skill-Share-Crawler---DL#26]
this is what it comes up with when i select either automatic auth or manual:

? What do you want to do ? 2 - Manual Auth
? Enter your Cookies check this issue https://github.com/tharyckgusmao/Skill-Share-Crawler---DL/issues/22 :
PS C:\Users\Vladimir\Downloads\Skill-Share-Crawler---DL-master\Skill-Share-Crawler---DL-master>

**please help**

**Comment by Scotley** [comment]
Observing the same issue.  I haven't managed to solve.  Powershell and CMD have the same result:

PS C:\Users\scotl\Documents\Skill-Share-Crawler---DL-master> npm run start

> skillshare_dl@1.0.0 start C:\Users\scotl\Documents\Skill-Share-Crawler---DL-master
> node index.js
  ____    _      _   _   _     ____    _                               ____    _
 / ___|  | | __ (_) | | | |   / ___|  | |__     __ _   _ __    ___    |  _ \  | |
 \___ \  | |/ / | | | | | |   \___ \  | '_ \   / _` | | '__|  / _ \   | | | | | |
  ___) | |   <  | | | | | |    ___) | | | | | | (_| | | |    |  __/   | |_| | | |___
 |____/  |_|\_\ |_| |_| |_|   |____/  |_| |_|  \__,_| |_|     \___|   |____/  |_____|
? What do you want to do ? 1 - Automatically Auth
? Enter your Skill Share e-mail address:
PS C:\Users\scotl\Documents\Skill-Share-Crawler---DL-master>

**Comment by syntaxhacker** [comment]
yep same problem for me too 😭😭😭

**Comment by tharyckgusmao** [comment]
Hellooo, please informs me your OS version, and a version of the node.

**Comment by Scotley** [comment]
Running  node v8.12.0 on windows 10.0.17134. Had the same issues with node 10.13.0.

**Comment by tharyckgusmao** [comment]
Do you mean that it automatically closes when you select an option?

**Comment by Scotley** [comment]
Correct, it returns back to the command prompt.

This issue will need to be solved for others, but tbh I don't need it anymore, I ended up writing a script to scrape their website and download directly from there.  Worked nicely but not robust enough to survive a DOM change so not worth putting up on github.

**Comment by Scotley** [comment]
No worries, it seems like a bit of an edge case. I just tried on a fresh install and can no longer reproduce the issue.

**Comment by fffuter** [comment]
The same here. Win 7 x64. Newly installed newest node.js
Installation and patching went well, but can't get it working after choosing manual/automatic option it's going back to command prompt. Even if Im going to choose option "exit" it's going back to command prompt and it's kind of frozzen. Thats it.  
There is no proper manual at all for this script, what is needed and so on, maybe that's the deal.

**Comment by fffuter** [comment]
It worked once, now after reboot is not working at all. It seems that script or installation is kind of bugged.

**Comment by tharyckgusmao** [comment]
I think the problem is with the lib "inquirer", in windows.

**Comment by fffuter** [comment]
Allright. That's odd that after installing babel it worked and I even could go to browsing what I want to download. I notice that script is working odd on cmd.exe, far better is working under some terminal emulator.
Do You mean inquirer.js or other library?

**Comment by arshakil** [comment]
First uninstall node.js and install this version      node-v8.12.0-x64.msi    
problem solve .........................

**Comment by bugrabayin** [comment]
> First uninstall node.js and install this version node-v8.12.0-x64.msi
> problem solve .........................
Thank you so much.

**Comment by bugrabayin** [comment]
> First uninstall node.js and install this version node-v8.12.0-x64.msi
> problem solve .........................
Thank you so much.

**Comment by bugrabayin** [comment]
this issue after entering the video ID

> ? Enter ID video Skill Share: 2062584672
undefined:1
undefined
^
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at logData (C:\Users\Seckin\Desktop\Skill-Share-Crawler---DL-master\app\components\FindIdVideo.js:61:18)
    at Request.request [as _callback] (C:\Users\Seckin\Desktop\Skill-Share-Crawler---DL-master\app\components\FindIdVideo.js:52:7)
    at self.callback (C:\Users\Seckin\Desktop\Skill-Share-Crawler---DL-master\node_modules\request\request.js:188:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\Users\Seckin\Desktop\Skill-Share-Crawler---DL-master\node_modules\request\request.js:884:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! skillshare_dl@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the skillshare_dl@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Seckin\AppData\Roaming\npm-cache\_logs\2019-08-15T09_54_38_611Z-debug.log

 and log
> 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle skillshare_dl@1.0.0~prestart: skillshare_dl@1.0.0
6 info lifecycle skillshare_dl@1.0.0~start: skillshare_dl@1.0.0
7 verbose lifecycle skillshare_dl@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle skillshare_dl@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Seckin\Desktop\Skill-Share-Crawler---DL-master\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\geckodriver;C:\Program Files\nodejs\;C:\Python\Python37\Scripts\;C:\Python\Python37\;C:\Users\Seckin\AppData\Local\Programs\Python\Launcher\;C:\Users\Seckin\AppData\Local\Microsoft\WindowsApps;C:\Users\Seckin\AppData\Roaming\npm
9 verbose lifecycle skillshare_dl@1.0.0~start: CWD: C:\Users\Seckin\Desktop\Skill-Share-Crawler---DL-master
10 silly lifecycle skillshare_dl@1.0.0~start: Args: [ '/d /s /c', 'node index.js' ]
11 silly lifecycle skillshare_dl@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle skillshare_dl@1.0.0~start: Failed to exec start script
13 verbose stack Error: skillshare_dl@1.0.0 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid skillshare_dl@1.0.0
15 verbose cwd C:\Users\Seckin\Desktop\Skill-Share-Crawler---DL-master
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
18 verbose node v8.12.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error skillshare_dl@1.0.0 start: `node index.js`
22 error Exit status 1
23 error Failed at the skillshare_dl@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
