### ISSUE TITLE
Can't download large courses

### ISSUE THREAD

**Issue by MoweME** [tharyckgusmao/Skill-Share-Crawler---DL#27]
I just wanted to download a course, but I got an error.
I think it's the size of the course, this is 126 videos.

`
  Video Python 3: A Beginners Guide to PytProgress

  Video #0            [--------------------] 0%
  Video #1            [||-----------------] 12%
  Video #2            [||-----------------] 13%
  Video #3            [|||||||||||||||||--] 87%
  Video #4            [--------------------] 0%
  Video #5            [--------------------] 0%
  Video #6            [|||----------------] 16%
  Video #7            [||||||-------------] 35%
  Video #8            [|||||||------------] 36%
  Video #9            [|||||--------------] 29%
  Video #10           [--------------------] 0%
  Video #11           [|||||||||||||||||||] 100%
  Video #12           [||||||||||||||||---] 84%
  Video #13           [||||||||-----------] 44%
  Video #14           [|||----------------] 16%
  Video #15           [||||||-------------] 35%
  Video #16           [|||----------------] 19%
  Video #17           [|------------------] 9%
  Video #18           [--------------------] 0%
  Video #19           [-------------------] 3%
  Video #20           [|------------------] 7%
  Video #21           [|------------------] 7%
  Video #22           [--------------------] 0%
  Video #23           [--------------------] 0%
  Video #24           [||||---------------] 22%
  Video #25           [|------------------] 9%
  Video #26           [||-----------------] 14%
  Video #27           [||||---------------] 22%
  Video #28           [||||||-------------] 33%
  Video #29           [||-----------------] 15%
  Video #30           [||-----------------] 15%
  Video #31           [|||----------------] 17%
  Video #32           [|------------------] 10%
  Video #33           [|||----------------] 20%
  Video #34           [||-----------------] 15%
  Video #35           [-------------------] 5%
  Video #36           [||-----------------] 13%
  Video #37           [--------------------] 0%
  Video #38           [||-----------------] 15%
  Video #39           [-------------------] 4%
  Video #40           [||-----------------] 15%
  Video #41           [|------------------] 6%
  Video #42           [--------------------] 0%
  Video #43           [--------------------] 0%
  Video #44           [--------------------] 0%
  Video #45           [||-----------------] 14%
  Video #46           [-------------------] 4%
  Video #47           [-------------------] 4%
  Video #48           [--------------------] 0%
  Video #49           [||-----------------] 14%
  Video #50           [--------------------] 0%
  Video #51           [|------------------] 9%
  Video #52           [--------------------] 0%
  Video #53           [|||||--------------] 27%
  Video #54           [--------------------] 0%
  Video #55           [--------------------] 0%
  Video #56           [|||||||||||||------] 69%
  Video #57           [--------------------] 0%
  Video #58           [--------------------] 0%
  Video #59           [||||||||||||||-----] 71%
  Video #60           [--------------------] 0%
  Video #61           [|------------------] 10%
  Video #62           [--------------------] 0%
  Video #63           [--------------------] 0%
  Video #64           [--------------------] 0%
  Video #65           [--------------------] 0%
  Video #66           [--------------------] 0%
  Video #67           [--------------------] 0%
  Video #68           [--------------------] 0%
  Video #69           [--------------------] 0%
  Video #70           [--------------------] 0%
  Video #71           [||||---------------] 24%
  Video #72           [-------------------] 2%
  Video #73           [--------------------] 0%
  Video #74           [--------------------] 0%
  Video #75           [||||||||||||||||||-] 95%
  Video #76           [--------------------] 0%
  Video #77           [-------------------] 4%
  Video #78           [--------------------] 0%
  Video #79           [|------------------] 9%
  Video #80           [--------------------] 0%
  Video #81           [--------------------] 0%
  Video #82           [--------------------] 0%
  Video #83           [--------------------] 0%
  Video #84           [||-----------------] 15%
  Video #85           [--------------------] 0%
  Video #86           [--------------------] 0%
  Video #87           [--------------------] 0%
  Video #88           [|||||||------------] 38%
  Video #89           [--------------------] 0%
  Video #90           [--------------------] 0%
  Video #91           [--------------------] 0%
  Video #92           [--------------------] 0%
  Video #93           [--------------------] 0%
  Video #94           [|||----------------] 20%
  Video #95           [--------------------] 0%
  Video #96           [|------------------] 6%
  Video #97           [--------------------] 0%
  Video #98           [--------------------] 0%
  Video #99           [--------------------] 0%
  Video #100          [-------------------] 4%
  Video #101          [|------------------] 7%
  Video #102          [|------------------] 9%
  Video #103          [|||----------------] 19%
  Video #104          [|||||||||||||------] 67%
  Video #105          [||-----------------] 12%
  Video #106          [||-----------------] 15%
  Video #107          [||||||-------------] 31%
  Video #108          [||||---------------] 21%
  Video #109          [--------------------] 0%
  Video #110          [-------------------] 4%
  Video #111          [--------------------] 0%
  Video #112          [|------------------] 6%
  Video #113          [|------------------] 9%
  Video #114          [|------------------] 9%
  Video #115          [|||||||------------] 39%
  Video #116          [-------------------] 2%
  Video #117          [||||---------------] 22%
  Video #118          [||-----------------] 13%
  Video #119          [|||----------------] 18%
  Video #120          [||||||||||---------] 52%
  Video #121          [||-----------------] 13%
  Video #122          [|||----------------] 16%
  Video #123          [-------------------] 3%
  Video #124          [||-----------------] 14%
  Video #125          [|------------------] 9%
  Video #126          [||-----------------] 11%

undefined:1
undefined
^

SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request.request [as _callback] (C:\Users\UserXY\Desktop\Skill-Share-Crawler---DL-master\app\components\DlPerId.js:61:30)
    at self.callback (C:\Users\UserXY\Desktop\Skill-Share-Crawler---DL-master\node_modules\request\request.js:188:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\Users\UserXY\Desktop\Skill-Share-Crawler---DL-master\node_modules\request\request.js:884:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! skillshare_dl@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the skillshare_dl@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\UserXY\AppData\Roaming\npm-cache\_logs\2018-10-14T12_28_34_209Z-debug.log

`

**Comment by MoweME** [comment]
This is the ClassID: 821742951

**Comment by dobrynski** [comment]
This still does not work.
