### ISSUE TITLE
Cant run the program!

### ISSUE THREAD

**Issue by ghost** [tharyckgusmao/Skill-Share-Crawler---DL#29]
PS C:\Skill-Share-Crawler---DL-master> npm run start

> skillshare_dl@1.0.0 start C:\Skill-Share-Crawler---DL-master
> node index.js

internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'webdriverio'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Skill-Share-Crawler---DL-master\node_modules\browsermob-proxy\index.js:6:21)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! skillshare_dl@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the skillshare_dl@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hp\AppData\Roaming\npm-cache\_logs\2018-11-22T18_27_55_075Z-debug.log

LOG FILE:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v10.13.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle skillshare_dl@1.0.0~prestart: skillshare_dl@1.0.0
6 info lifecycle skillshare_dl@1.0.0~start: skillshare_dl@1.0.0
7 verbose lifecycle skillshare_dl@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle skillshare_dl@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Skill-Share-Crawler---DL-master\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\go\bin;C:\Program Files\nodejs\;C:\Users\hp\AppData\Local\Microsoft\WindowsApps;C:\Users\hp\AppData\Roaming\npm
9 verbose lifecycle skillshare_dl@1.0.0~start: CWD: C:\Skill-Share-Crawler---DL-master
10 silly lifecycle skillshare_dl@1.0.0~start: Args: [ '/d /s /c', 'node index.js' ]
11 silly lifecycle skillshare_dl@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle skillshare_dl@1.0.0~start: Failed to exec start script
13 verbose stack Error: skillshare_dl@1.0.0 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid skillshare_dl@1.0.0
15 verbose cwd C:\Skill-Share-Crawler---DL-master
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
18 verbose node v10.13.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error skillshare_dl@1.0.0 start: `node index.js`
22 error Exit status 1
23 error Failed at the skillshare_dl@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by tharyckgusmao** [comment]
Hello try, 
`npm install` 
`npm install -S webdriverio`
