### ISSUE TITLE
Linux Mint / It doesn't run - Syntax Error

### ISSUE THREAD

**Issue by freaky-m0** [tharyckgusmao/Skill-Share-Crawler---DL#47]
Hi maybe I have the wrong version of nodejs or something? It drops a syntax error. Could anybody help me to get this running? thx in advance!

`

> skillshare_dl@1.0.0 start /home/xx/Downloads/skill
> node index.js

/home/xx/Downloads/skill/node_modules/got/dist/source/create.js:101
    got.paginate = async function* (url, options) {
                                 ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/xx/Downloads/skill/node_modules/got/dist/source/index.js:7:18)

npm ERR! Linux 5.3.0-45-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! skillshare_dl@1.0.0 start: `node index.js`
npm ERR! Exit status 1
`

**Comment by freaky-m0** [comment]
The default version of nodejs in latest ubuntu lts (and mint) seems to be a bit old. I installed the latest stable from the nodesource repos / documentation and it worked fine.

https://tecadmin.net/install-latest-nodejs-npm-on-ubuntu/
