### ISSUE TITLE
no longer working

### ISSUE THREAD

**Issue by shywolf91** [tharyckgusmao/Skill-Share-Crawler---DL#52]
I have tried both auto auth (google google recaptcha or facebook) and manual auth. When I do manual auth I get:
Skill-Share-Crawler---DL-master\app\components\GetAllVideos.js:81
            if(dataClasses.spaces[0].next_page_url == null){
                                 ^

TypeError: Cannot read property '0' of undefined
    at Request.request [as _callback] (C:\Users\Legoshi\Desktop\Skill-Share-Crawler---DL-master\app\components\GetAllVideos.js:81:34)
    at Request.self.callback (C:\Users\Legoshi\Desktop\Skill-Share-Crawler---DL-master\node_modules\request\request.js:188:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\Legoshi\Desktop\Skill-Share-Crawler---DL-master\node_modules\request\request.js:1171:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\Legoshi\Desktop\Skill-Share-Crawler---DL-master\node_modules\request\request.js:1091:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! skillshare_dl@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the skillshare_dl@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Legoshi\AppData\Roaming\npm-cache\_logs\2020-08-23T02_32_27_218Z-debug.log

**Comment by lakimakromedia** [comment]
same here
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.17.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle skillshare_dl@1.0.0~prestart: skillshare_dl@1.0.0
6 silly lifecycle skillshare_dl@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle skillshare_dl@1.0.0~start: skillshare_dl@1.0.0
8 verbose lifecycle skillshare_dl@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle skillshare_dl@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\SkillShare\node_modules\.bin;C:\Users\lakibee\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\lakibee\bin;C:\Python38\Scripts;C:\Python38;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft SQL Server\120\DTS\Binn;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit;C:\Program Files\Git\cmd;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs;C:\Users\lakibee\AppData\Local\Microsoft\WindowsApps;C:\Users\lakibee\AppData\Local\GitHubDesktop\bin;C:\Users\lakibee\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
10 verbose lifecycle skillshare_dl@1.0.0~start: CWD: C:\SkillShare
11 silly lifecycle skillshare_dl@1.0.0~start: Args: [ '/d /s /c', 'node index.js' ]
12 silly lifecycle skillshare_dl@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle skillshare_dl@1.0.0~start: Failed to exec start script
14 verbose stack Error: skillshare_dl@1.0.0 start: `node index.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid skillshare_dl@1.0.0
16 verbose cwd C:\SkillShare
17 error Windows_NT 10.0.18363
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
19 error node v6.17.1
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error skillshare_dl@1.0.0 start: `node index.js`
22 error Exit status 1
23 error Failed at the skillshare_dl@1.0.0 start script 'node index.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the skillshare_dl package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node index.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs skillshare_dl
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls skillshare_dl
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Xtendera** [comment]
Same here
